# Generated by Django 3.2 on 2021-04-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundstatus',
            options={'verbose_name': 'Статус песни'},
        ),
    ]
