# Generated by Django 3.2 on 2021-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='index',
            field=models.IntegerField(default=64),
        ),
    ]
