# Generated by Django 3.2 on 2021-04-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0002_alter_soundstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundstatus',
            options={'verbose_name': 'Статус песни', 'verbose_name_plural': 'Статус песен'},
        ),
    ]
