# Generated by Django 3.2 on 2021-04-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0003_alter_soundstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundstatus',
            options={'verbose_name': 'Статусы песни', 'verbose_name_plural': 'Статус песен'},
        ),
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('description', models.TextField()),
                ('status', models.ForeignKey(default='wait_moder', on_delete=django.db.models.deletion.CASCADE, to='clubbisenes.soundstatus')),
            ],
        ),
    ]
