# Generated by Django 3.2 on 2021-05-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0008_auto_20210502_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'verbose_name': 'ProfileUser', 'verbose_name_plural': 'ProfileUser'},
        ),
    ]
