# Generated by Django 3.2 on 2021-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0009_alter_userprofilemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
