# Generated by Django 3.2 on 2021-05-02 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubbisenes', '0010_userprofilemodel_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounds',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
