# Generated by Django 3.2 on 2021-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0012_shiftuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftuser',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
