# Generated by Django 3.2 on 2021-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0013_alter_shiftuser_date_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftuser',
            name='day_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
