# Generated by Django 3.2 on 2021-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0014_shiftuser_day_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
