# Generated by Django 3.2 on 2021-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0015_userprofilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
