# Generated by Django 3.2 on 2021-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0017_remove_shiftuser_day_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounds',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
