# Generated by Django 3.2 on 2021-07-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubbisenes', '0018_alter_sounds_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
